### ISSUE TITLE
Churn on particular commit [QUESTION]

### ISSUE THREAD

**Issue by MilanRgm** [flacle/truegitcodechurn#10]
First of all, I appreciate you for creating this awesome package. I have one question. If you have time, can you please tell me how you would calculate the churn of a particular commit? I mean, suppose, I committed 3 commits and I need to find the churn for each separate commit. The thing is now I need to check if the changes has been done within 21 days in that particular commit. How can I make sure the churn is based on 21 days for each commit?

**Comment by flacle** [comment]
Hi Milan,

My apologies for the delay in replying to your question. You pose an interesting problem, at the moment the script does not support search by commit, solely by author. This is because churn is a metric that is usually used to measure the performance of a particular team member, and usually that implies looking at a project over a period of time by author. The idea is here to openly discuss for a project issues that team members encounter. For example, if you find yourself reimplementing something specific within a specific class/file, than that maybe suggests a larger discussion where more significant changes are needed on the business logic (model/architecture) side of things.

But to come back to your question, it can be done in the future, but it requires quite some changes. Searching by a range of commits would basically have to complement searching by dates, as each commit has a timestamp. I will create a new issue, but at the moment cannot guarantee any date by when this can be done. You are welcome to send a pull request in case you would like to contribute to the project :)

-F

**Comment by flacle** [comment]
Interesting use case indeed. Issue #11 created.

**Comment by MilanRgm** [comment]
Thank you @flacle for your response and taking this problem into consideration. I have one confusion while calculating churn for a particular commit. Let's say today I committed in this repo where I have changed two files. As per most of the article and especially as per pluralsight, "Code Churn is when an engineer rewrites or deletes their own code that is less than 3 weeks old". My confusion is how can we track the changes that I did in this commit is "less than 3 weeks old".

Should we first list the files where changes has been done on this commit and then find out all those commits until 3 weeks where those files has been touched to get the difference? 

This(changes done in less than 3 weeks) is where I am totally confused. Can you help me to clarify my confusion?

**Comment by flacle** [comment]
Hi @MilanRgm I've opted not to limit the time window of 3 weeks as stated [here](https://help.pluralsight.com/help/what-is-churn). The reason being (and this is debatable) is that velocities of projects can vary a lot. It would be best to have the product owner or team lead set this limit based on experience. For example, you might have an external team member that is working once a week for a couple of hours, and within that same project another team member who is working every day, so here you are free to decide the time window by setting the start and end dates per team member. Now there aren't custom date strings, so you can't state something like `after="3 weeks ago"` but this can be a new feature to consider for the future. One way you can automate this now is to for example load the Python script via another Bash/PowerShell script and have the date be set programmatically.
For example, for Bash you can try something like:

    #!/bin/bash
    before=$("2021-08-25")
    after=$(date --date="${before} -21 day" +%Y-%m-%d)
    python ./gitcodechurn.py after="$after" before="$before" author="an author" dir="/Users/myname/myrepo" -exdir="excluded-directory"

I haven't tested this, but the basic idea is that you programmatically fill in the date parameters and call the Python script from the command line.

Small note: the script automatically looks at files within a project as it searches by author, so no need to list files separately.

Hope this clarifies your confusion!

**Comment by flacle** [comment]
Closing issue due to no further activity.
