### ISSUE TITLE
understanding the jargon used in the code

### ISSUE THREAD

**Issue by tushantKrispcall** [flacle/truegitcodechurn#8]
Sorry for a naive question. Can you please clarify what exactly is `contribution` and `churn` in this output, please?

```
contribution: 11000
churn: -900
```

Is here contribution means totally new work without any changes in the code? I mean brand new code that does not replace any older code?

Is here churn means only the changes in the same lines of code?

I think it will be better to consider efficiency and legacy refactor.

**Comment by flacle** [comment]
Hi @tushantKrispcall ,

It's not naive at all, the terminology is not common. Regarding your question your understanding is correct! I was inspired by this [article](https://www.pluralsight.com/blog/teams/why-code-churn-matters) that states that:
> "Code churn is when an engineer rewrites their own code in a short period of time. Think of it as writing a postcard and then tearing it up and writing it again, and then again."

_Side-note: because "a short period of time" is subjective anyone is able to determine this on their own by specifying the start and end dates._

The word 'contribution' defines indeed new lines of code that got introduced and did not receive any edits within the specified period of the time. So to comeback to your example:
````
contribution: 11000
churn: -900
````
means that for a specified time period there were 11K new lines added to the code-base and 900 lines that already existed before the starting date got edited by a particular author (or any author if left blank).

I'm not sure if 'legacy' and 'efficiency' are better suited. If you look [here](https://en.wikipedia.org/wiki/Legacy_code), legacy is defined as "source code that relates to a no-longer supported or manufactured operating system or other computer technology". Efficiency in my opinion is defined as optimizing something that already exists for a particular purpose, like execution performance for example. I think it can get confusing. Then again the definition of churn within the context of business metrics is something entirely [different](https://www.profitwell.com/customer-churn/calculate-churn-rate) :upside_down_face:.

You can always fork/clone the repository and change the definitions on lines 110-111 of [gitcodechurn.py](https://github.com/flacle/truegitcodechurn/blob/master/gitcodechurn.py#L110).

Hope this helps and my apologies for the delayed response to your question.
